openapi: 3.0.0
info:
  version: v3.9.0
  title: Liberkee Voucher API

tags:
  - name: Digital Key Voucher Management
    description: Vehicle related actions and end points.

paths:
  /vouchers:
    get:
      summary: "Get all vouchers that the user created. Optionally, filter for
        a single vehicle."

      parameters:
        - in: query
          name: external_device_ref
          schema:
            type: string
          description: A String value identifying the vehicle.

      security:
        - oAuth:
          - create_voucher_code_for_device

      responses:
        '200':
          description: |
            The "KeyVoucher" object with the Voucher code and meta
            information for the digital key.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KeyVouchers'
        '400':
          description: |
            This code indicates that one of your parameters caused an issue. 
            Read the response for more details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoucherParameterClientError'
        '401':
          description: |
            Please authorize first to use this route.
        '403':
          description: |
            You are not allowed to use this route or access the specified vehicle.
      tags:
        - Digital Key Voucher Management


  /vouchers/create:
    post:
      summary: Create a Voucher for digital keys.
      operationId: getVoucherCode
      description: |
        Request a Voucher for usage in the liberkee® app.
      requestBody:
        content:
          application/json:
            schema:
             $ref: '#/components/schemas/VoucherParameter'

      security:
        - oAuth:
          - create_voucher_code_for_device

      responses:
        '201':
          description: |
            The "KeyVoucher" object with the Voucher code and meta
            information for the digital key.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KeyVoucher'
        '400':
          description: |
            This code indicates that one of your parameters caused an issue. 
            Read the response for more details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoucherParameterClientError'
        '401':
          description: |
            Please authorize first to use this route.
        '403':
          description: |
            You are not allowed to use this route.
        '404':
          description: | 
            The external device reference you specified was not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoucherParameterNotFoundError'
      tags:
        - Digital Key Voucher Management


  /vouchers/{voucher_id}/update:
    post:
      summary: "Update the Voucher for 'voucher_id'"
      operationId: updateVoucherCode
      description: |
        Update the Voucher for voucher_id and all the assiciated digital keys.
        This is useful to update or change your booking; for example a booking
        can be extended or invalidated. To cancel a booking, use vouchers with
        the method DELETE.
      parameters:
        - in: path
          name: voucher_id
          required: true
          schema:
            type: string
          description: The Voucher ID

      requestBody:
        content:
          application/json:
            schema:
             $ref: '#/components/schemas/VoucherParameter'

      security:
        - oAuth:
          - create_voucher_code_for_device

      responses:
        '201':
          description: |
            The "KeyVoucher" object with the Voucher code and meta
            information for the digital key.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KeyVoucher'
        '400':
          description: |
            This code indicates that one of your parameters caused an issue. 
            Read the response for more details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoucherParameterClientError'
        '401':
          description: |
            Please authorize first to use this route.
        '403':
          description: |
            You are not allowed to use this route.
        '404':
          description: | 
            The external device reference you specified was not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoucherParameterNotFoundError'
      tags:
        - Digital Key Voucher Management

  /vouchers/{voucher_id}/revoke:
    post:
      summary: "Revoke the Voucher for 'voucher_id'"
      operationId: revokeVoucherCode
      description: |
        Revoke all access that was redeemed through this Voucher and deny any
        future attempts of redeeming access through it.
      parameters:
        - in: path
          name: voucher_id
          required: true
          schema:
            type: string
          description: The Voucher ID

      security:
        - oAuth:
          - create_voucher_code_for_device

      responses:
        '200':
          description: |
            The "KeyVoucher" object with the Voucher code and meta
            information for the digital key.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KeyVoucher'
        '400':
          description: |
            This code indicates that one of your parameters caused an issue. 
            Read the response for more details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoucherParameterClientError'
        '401':
          description: |
            Please authorize first to use this route.
        '403':
          description: |
            You are not allowed to use this route.
        '404':
          description: | 
            The external device reference you specified was not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoucherParameterNotFoundError'
      tags:
        - Digital Key Voucher Management

  /vouchers/{voucher_id}:
    get:
      summary: "Get the Voucher with the given ID."

      parameters:
        - in: path
          name: voucher_id
          required: true
          schema:
            type: string
          description: The Voucher ID

      security:
        - oAuth:
          - create_voucher_code_for_device

      responses:
        '200':
          description: |
            The "KeyVoucher" object with the Voucher code and meta
            information for the digital key.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KeyVoucher'
        '400':
          description: |
            This code indicates that one of your parameters caused an issue. 
            Read the response for more details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoucherParameterClientError'
        '401':
          description: |
            Please authorize first to use this route.
        '404':
          description: |
            The requested Voucher could not be found. It either does not exist or you have no
            access to it.
      tags:
        - Digital Key Voucher Management

    delete:
      summary: "Delete a Voucher and all digital keys associated with it."

      parameters:
        - in: path
          name: voucher_id
          required: true
          schema:
            type: string
          description: The Voucher ID

      responses:
        '200':
          description: |
            The "KeyVoucher" object was successfully deleted.
        '400':
          description: |
            This code indicates that one of your parameters caused an issue. 
            Read the response for more details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoucherParameterClientError'
        '401':
          description: |
            Please authorize first to use this route.
        '403':
          description: |
            You are not allowed to use this route.
      tags:
        - Digital Key Voucher Management


security:
  - oAuth:
    - create_voucher_code_for_device


components:
  securitySchemes:
    oAuth:
      type: oauth2
      description: |
        This API uses OAuth 2.0 with the client credential flow.
        [More info](https://api.example.com/docs/auth).
        Contact us if you want to receive a client for using this API.
      flows:
        clientCredentials:
          tokenUrl: "https://identity.prod.liberkee.com/connect/token"
          scopes:
            api.liberke: Access to the liberkee API.


  schemas:
    CustomActionConfiguration:
      description: |
        This object is used inside a custom action. You can specify HTTP
        requests with this configuration that will get passed into the 
        HTTP request mechanism we support inside liberkee® app. Also, the
        OpenInBrowser option gives you the abilty to open a page of your
        choice. Use the url parameter to pass along additional query
        parameters that your end point can interpret.
      type: object
      properties:
        action_type:
          type: string
          enum: ["HttpRequest", "OpenInBrowser"]
        url:
          type: string
          format: url
        http_method:
          type: string
          enum: [POST, GET, UPDATE, DELETE]
        headers:
          type: object
        body:
          type: object


    CustomAction:
      description: |
        This is the action that will be enabled by the button. We 
        support the action method 'HttpRequest' at this point. We
        will make sure that the request is passed to the target in URL 
        as specified. This is useful when you want a certain behaviour
        that we do not support out-of-the-box.
      type: object
      properties:
        caption:
          type: string
        dialog_type:
          description: |
            Setting this will select the dialog type that the user will
            see after pressing this button.
            
            By selecting 'Confirmation' a simple confirm dialog is 
            presented to the user and the text from the 'text' property
            is displayed. The user can confirm or cancel this request.
            
            By selecting 'Information' the user will se a pop-up that
            displays the specified information and executes the specified
            request.
          type: string
          enum: ["Confirmation", "Information"]
        text:
          description: |
            This is the text, the user gets displayed when clicking on
            the button you customized.
          type: string
        icon:
          description: |
            This selects the icon the button will display to your user.
            
            See our documentation for more details of the icons.
          type: string
          enum: ["None", "Sharing", "Edit", "EndBooking", "ExtendBooking"]
        configuration:
          $ref: '#/components/schemas/CustomActionConfiguration'


    KeyVoucher:
      description: "Key Voucher for digital keys."
      type: object
      properties:
        id:
          description: |
            The id of the Voucher.
          type: string
          pattern: "^[a-zA-Z0-9]{20}$"
        external_device_ref:
          description: |
           The reference to the device a Voucher is connected to.
           type: string
        Voucher:
          description: |
            The string to present to your user; it is designed to be
            understood by the mobile operating system to open the liberkee® app.
          type: string
          pattern: "^https://liberkee.com:/redeem/[a-zA-Z0-9]{20}$"
        key_valid_from:
          description: |
            The start time the digital key that this Voucher
            represents becomes usable, expressed in extended ISO 8601.
          type: string
          format: date-time
        key_valid_to:
          description: |
            The start time the digital key that this Voucher
            represents stops being usable, expressed in extended ISO 8601.
          type: string
          format: date-time
        expires_at:
          description: |
            The time when the Voucher code becomes invalid,
            expressed as extended ISO 8601.
          type: string
          format: date-time
        revoked:
          description: |
            Indicates if the Voucher has been revoked.
          type: boolean
        revoked_at:
          description: |
            The time the Voucher has been revoked at. null if the Voucher has
            not been revoked.
          type: string
          format: date-time
          nullable: true

      example:
        id: "adventure11acmerental"
        external_device_ref: "adventurecar_11@acmerental.com"
        Voucher: "https://liberkee.com/redeem/adventure11acmerental"
        key_valid_from: "2021-10-30T07:30:00Z"
        key_valid_to: "2021-10-30T10:30:00Z"
        expires_at: "2021-10-31T01:00:00Z"
        revoked: false
        revoked_at: null

    KeyVouchers:
      description: "List of Key Vouchers for digital keys."
      type: object
      properties:
        items:
          $ref: '#/components/schemas/KeyVoucher'

      example:
        - id: "adventure11acmerental"
          external_device_ref: "adventurecar_11@acmerental.com"
          Voucher: "https://liberkee.com/redeem/adventure11acmerental"
          key_valid_from: "2021-10-30T07:30:00Z"
          key_valid_to: "2021-10-30T10:30:00Z"
          expires_at: "2021-10-31T01:00:00Z"
          revoked: false
          revoked_at: null
        - id: "acmerental1"
          external_device_ref: "acmerental1@acmerental.com"
          Voucher: "https://liberkee.com/redeem/acmerental_global"
          key_valid_from: "2021-10-30T07:30:00Z"
          key_valid_to: "2021-10-30T10:30:00Z"
          expires_at: "2021-10-31T01:00:00Z"
          revoked: true
          revoked_at: "2021-10-30T08:00:00Z"


    VoucherParameterClientError:
      type: object
      properties:
        details:
          type: string
      example:
        details: Sorry, we did not understand your request.


    VoucherParameterNotFoundError:
      type: object
      properties:
        details:
          type: string
      example:
        details: Your vehicle reference 'the-fast-car' was not found.


    DeviceDetailEntry:
      type: object
      properties:
        title:
          type: string
          pattern: "^.{1,30}$"
        value:
          type: string
          pattern: "^.{1,50}$"


    VoucherParameter:
      type: object
      properties:
        external_device_ref:
          description: |
            This value is used to identify the device (e.g. car) you want to
            retrieve a digital key Voucher for. The reference can be any string
            you have specified as reference for the device in our system.
            In order to obtain a Voucher for a digital key for that device,
            you have to be allowed to do it. This means that you have to be the
            owner of that device or must be allowed by the owner to reshare 
            the device.
          type: string
          nullable: false

        valid_for:
          description: |
            Describes the time span the Voucher will be valid for; please use
            the ISO 8601 notation for the timespan. For example "PT30M" for a
            duration of 30 minutes.
          type: string
          format: time-span
          nullable: false

        concurrent_redeem_limit:
          description: |
            This limit specifies how often a single Voucher can be claimed. A 
            value -1 or 0 counts as infinite, so a Voucher can be claimed 
            an unlimited ammount of times.
          type: integer
          minimum: -1
          maximum: 2000
          nullable: false

        key_valid_from:
          description: |
            You need to specify when the key becomes valid (usable for a customer)
            by setting this field. Please use extended ISO 8601 conform time stamps.
            
            IMPORTANT This value also determines when the exact device position
            becomes visible to a person that has access to the digital key, if the
            device supports such capabilities. The digital key and the entry
            assiciated with it in liberkee® app, is immeadiatley visible in the
            device list of the app.
          type: string
          format: date-time
          nullable: false

        key_valid_to:
          description: |
            You must specify when the key becomes invalid (no longer usable for a 
            customer) by setting this field. Please use extended ISO 8601 conform
            time stamp.
          type: string
          format: date-time
          nullable: false

        device_display_name:
          description: |
            You can specify the display name of the device that is shown to the
            customer after claiming a device.
          type: string
          pattern: "^.{1,50}$"
          nullable: false

        display_message:
          description: |
            You can specify a massage that a customer gets presented,
            when claiming the key and viewing the digital key inside the
            liberkee® app; this allows you to add a custum flavor to the
            experience your customers will have.
          type: string
          pattern: "^.{1,50}$"
          nullable: false

        device_details:
          description: |
            This is a list of 'DeviceDetailEntry' that allows you to
            control the bottom-section of the device-detail screen.
            Every entry will be rendered as table and title-value pair.
          type: array
          items:
            $ref: '#/components/schemas/DeviceDetailEntry'
          nullable: false

        custom_branding:
          description: |
            Add this if you want to have a custom branding inside the liberkee®
            app for this key; if "" is given, the branding will be the liberkee's
            default; if you are interested in a custom branding, please contact
            us and have a look at our [documentation](https://www.notion.so/Integrations-21c83bb335f74526865ea57fc63949fe).
          type: object
          properties:
            branding_id:
              description: |
                Specify the identifier of the banding you want to create you can
                use any UTF-8 compatible string.
              type: string
              pattern: "^.{1,50}$"
            background_image_url:
              description: |
                Specify the URL of the image you want to use in the
                branding; the image be displayed inside the view of your key.
              type: string
              format: url
            company_name:
              description: |
                This is the company name you want the user to see in view.
              type: string
              pattern: "^.{1,75}$"
            support_hotline:
              description: |
                Specify this phone number to enable the feature to call the
                support; you can specify any number you like; this will not be
                visible to the user; if you want to have it visible, then please
                set the 'device_devtails' above.
              type: string
          nullable: false

        custom_actions:
          description: |
            We allow you to customize the experience further by overriding
            the funcitons in the vehicle interaction screen. For example you
            want the user to be able to end the booking from within the app?
            You can do that by setting a custom action that performs that
            request.
            
            The intended purpose of this to extend liberkee® app to fit into
            your exitsting workflows.
          type: array
          items:
            $ref: '#/components/schemas/CustomAction'
          nullable: false

        user_permissions:
          description: |
            Specify what a customer is allowed to do with this key by specifying
            the attributes for key handling.
          type: object
          properties:
            allow_resharing:
              type: boolean
              description: |
                This is a flag to control the resharing behaviour of the 
                Voucher; if this is set to 'true' the Voucher can be shared as 
                many times as specified in the 'resharing_allowed_n_times'
                property; setting this to 'true' while not specifiyng a number
                for 'resharing_allowed_n_times' will result in the same behaviour
                as setting this value to 'false'.
              default: "false"
              nullable: false
            allow_resharing_n_times:
              description: |
                The number of times a Voucher can be used to obtain a digital
                key; every _new_ user, that redeems the Voucher will substract
                one from this count; a single user redeeming the Voucher
                multiple times, will have no effect; if this value reaches 0,
                the Voucher can no longer be redeemed.
              type: number
              format: integer
              default: 0
              nullable: false
          nullable: false

      example:
        external_device_ref: "adventurecar_11@acmerental.com"
        valid_for: "PT30M"
        concurrent_redeem_limit: 1
        key_valid_from: "2021-01-01T00:00:00Z"
        key_valid_to: "2021-01-11T00:00:00Z"
        device_display_name: "Landrover Defender"
        display_message: "Hejsan, Adventurer 🏕"
        device_details:
          - license_plate: "RE CG 1234"
          - emergency_contact: "+49172-555-3386"
          - contact_support: "+49172-555-3333"

        custom_branding:
          branding_id: "RentalDotComBrand_1"
          background_image_url: "https://images.unsplash.com/photo-1502489597346-dad15683d4c2"
          company_name: "ACME Adventure Rentals"
          support_hotline: "+49172-555"

        custom_actions:
          - caption: "End the booking"
            dialog_type: "Confirmation"
            text: "Do you really want to end the booking?"
            icon: "EndBooking"
            configuration:
              action_type: "HttpRequest"
              url: "https://acme-rental.com/bookings/end"
              http_method: "POST"
              headers:
                authorization: "token"
              body:
                booking_reference: "ACMA Rental with ID: 1234"

          - caption: "Extend booking"
            dialog_type: "Information"
            text: "Your booking has been extended."
            icon: "ExtendBooking"
            configuration:
              action_type: "HttpRequest"
              url: "https://acme-rental.com/bookings/extend"
              http_method: "POST"
              headers:
                authorization: "token"
              body:
                booking_reference: "ACMA Rental with ID: 1234"

        user_permissions:
          allow_resharing: "false"
          allow_resharing_n_times: 0
